model_type: DartsTFTModel
input_chunk_length: 7
output_chunk_length: 5
hidden_size: 32
dropout: 0.1            
lstm_layers: 2          
batch_size: 32          
n_epochs: 1           
random_state: 42
quantiles: [0.1, 0.5, 0.9]
num_samples: 100